# pg_aggregate = {}
# Aggregate kind: n for “normal” aggregates, o for “ordered-set” aggregates, or h for “hypothetical-set” aggregates
pg_aggregate.aggkind = { ty="PgAggregateAggkind", exp="PgAggregateAggkind::pg_from_char(pg_aggregate.aggkind)", pgEnum="'n' => Normal, 'o' => OrderedSet, 'h' => HypotheticalSet" }
# Whether aggfinalfn modifies the transition state value: r if it is read-only, s if the aggtransfn cannot be applied after the aggfinalfn, or w if it writes on the value
pg_aggregate.aggfinalmodify = { ty="PgAggregateAggfinalmodify", exp="PgAggregateAggfinalmodify::pg_from_char(pg_aggregate.aggfinalmodify)", pgEnum="'r' => ReadOnly, 's' => CannotApply, 'w' => Writes" }
# Like aggfinalmodify, but for the aggmfinalfn
pg_aggregate.aggmfinalmodify = { ty="PgAggregateAggmfinalmodify", exp="PgAggregateAggmfinalmodify::pg_from_char(pg_aggregate.aggmfinalmodify)", pgEnum="'r' => ReadOnly, 's' => CannotApply, 'w' => Writes" }
pg_aggregate.aggtransspace = 'skip'
pg_aggregate.aggmtransspace = 'skip'

# pg_am = {}
# t = table (including materialized views), i = index.
pg_am.amtype = { ty="PgAmAmtype", exp="PgAmAmtype::pg_from_char(pg_am.amtype)", pgEnum="'t' => Table, 'i' => Index" }

# pg_amop = {}
# Operator purpose, either s for search or o for ordering
pg_amop.amoppurpose = { ty="PgAmopAmoppurpose", exp="PgAmopAmoppurpose::pg_from_char(pg_amop.amoppurpose)", pgEnum="'s' => Search, 'o' => Ordering" }

pg_amproc = {}

pg_attrdef = 'todo'
# pg_attrdef.adbin = { sel="pg_get_expr(adbin, adrelid)", ty="Str" }

pg_attribute = 'todo'
# pg_attribute.attisdropped = { filters=["not attisdropped"] }
# pg_attribute.attcacheoff = 'skip'

# pg_roles = {}
pg_roles.rolpassword = 'skip'
pg_roles.rolvaliduntil = { ty="Option<chrono::DateTime<chrono::FixedOffset>>" }

pg_auth_members = {}

# pg_cast = {}
# Indicates what contexts the cast can be invoked in. e means only as an explicit cast (using CAST or :: syntax). a means implicitly in assignment to a target column, as well as explicitly. i means implicitly in expressions, as well as the other cases.
pg_cast.castcontext = { ty="PgCastCastcontext", exp="PgCastCastcontext::pg_from_char(pg_cast.castcontext)", pgEnum="'e' => Explicit, 'a' => ImplicitAssignment, 'i' => Implicit" }
# Indicates how the cast is performed. f means that the function specified in the castfunc field is used. i means that the input/output functions are used. b means that the types are binary-coercible, thus no conversion is required.
pg_cast.castmethod = { ty="PgCastCastmethod", exp="PgCastCastmethod::pg_from_char(pg_cast.castmethod)", pgEnum="'f' => Castfunc, 'i' => IOFunc, 'b' => BinaryCoercible" }

# pg_class = {}
pg_class.relnamespace = { filters=["relnamespace::regnamespace != 'pg_toast'::regnamespace"] }
pg_class.relallvisible = 'skip'
pg_class.relam = { nullable=true }
pg_class.relfilenode = 'skip'
pg_class.relhasindex = 'skip'
pg_class.relispopulated = 'skip'
pg_class.relpages = 'skip'
pg_class.relpartbound = { sel="pg_get_expr(relpartbound, pg_class.oid)", ty="Option<Str>", exp="pg_class.relpartbound.map(Into::into)" }
pg_class.relrewrite = 'skip'
pg_class.reltoastrelid = 'skip'
pg_class.reltuples = 'skip'
# p = permanent table/sequence, u = unlogged table/sequence, t = temporary table/sequence
pg_class.relpersistence = { ty="PgClassRelpersistence", exp="PgClassRelpersistence::pg_from_char(pg_class.relpersistence)", pgEnum="'p' => Permanent, 'u' => Unlogged, 't' => Temporary" }
# r = ordinary table, i = index, S = sequence, t = TOAST table, v = view, m = materialized view, c = composite type, f = foreign table, p = partitioned table, I = partitioned index
pg_class.relkind = { ty="PgClassRelkind", exp="PgClassRelkind::pg_from_char(pg_class.relkind)", pgEnum="'r' => Ordinary, 'i' => Index, 'S' => Sequence, 't' => Toast, 'v' => View, 'm' => MaterializedView, 'c' => CompositeType, 'f' => ForeignTable, 'p' => PartitionedTable, 'I' => PartitionedIndex" }
# Columns used to form “replica identity” for rows: d = default (primary key, if any), n = nothing, f = all columns, i = index with indisreplident set (same as nothing if the index used has been dropped)
pg_class.relreplident = { ty="PgClassRelreplident", exp="PgClassRelreplident::pg_from_char(pg_class.relreplident)", pgEnum="'d' => Default, 'n' => Nothing, 'f' => AllColumns, 'i' => Index " }

pg_collation = 'todo'

pg_constraint = 'todo'

pg_conversion = 'todo'

pg_database = 'manual'

pg_db_role_setting = 'manual'

# pg_default_acl = {}
# Type of object this entry is for: r = relation (table, view), S = sequence, f = function, T = type, n = schema
pg_default_acl.defaclobjtype = { ty="PgDefaultAclDefaclobjtype", exp="PgDefaultAclDefaclobjtype::pg_from_char(pg_default_acl.defaclobjtype)", pgEnum="'r' => Relation, 'S' => Sequence, 'f' => Function, 'T' => Type, 'n' => Schema" }

pg_depend = 'todo'

pg_description = 'todo'

pg_enum = 'todo'

pg_event_trigger = 'todo'

pg_extension = 'todo'

pg_foreign_data_wrapper = 'todo'

pg_foreign_server = 'todo'

pg_foreign_table = 'todo'

pg_index = 'todo'

pg_inherits = 'todo'
# pg_inherits.inhseqno

pg_init_privs = 'todo'

pg_language = {}

# pg_namespace = {}
pg_namespace.nspname = { filters=["nspname != 'pg_toast'"] }

pg_opclass = 'todo'

pg_operator = 'todo'

pg_opfamily = 'todo'

pg_parameter_acl = 'todo'

pg_partitioned_table = 'todo'

pg_policy = 'todo'

pg_proc = 'todo'

pg_publication = 'todo'

pg_publication_namespace = 'todo'

pg_publication_rel = 'todo'

pg_range = 'todo'

pg_replication_origin = 'todo'

pg_rewrite = 'todo'

# pg_seclabel = 'todo'

pg_sequence = 'todo'

pg_shdepend = 'todo'

pg_shdescription = 'todo'

# pg_shseclabel = 'todo'

pg_statistic_ext = 'todo'
# pg_statistic_ext.stxstattarget = { nullable=true }

pg_subscription = 'todo'

pg_trigger = 'todo'
# pg_trigger.tgtype = { ty="i16" }

pg_ts_config = 'todo'

pg_ts_config_map = 'todo'
# pg_ts_config_map.maptokentype = { ty="i16" }
# pg_ts_config_map.mapseqno = { ty="i16" }

pg_ts_dict = 'todo'

# pg_type = {}
pg_type.typlen = { ty="i16" }
pg_type.typdefaultbin = { sel="pg_get_expr(typdefaultbin, 0)", ty="Option<Str>", exp="pg_type.typdefaultbin.map(Into::into)" }
# typtype is b for a base type, c for a composite type (e.g., a table's row type), d for a domain, e for an enum type, p for a pseudo-type, r for a range type, or m for a multirange type. See also typrelid and typbasetype.
pg_type.typtype = { ty="PgTypeTyptype", exp="PgTypeTyptype::pg_from_char(pg_type.typtype)", pgEnum="'b' => Base, 'c' => Composite, 'd' => Domain, 'e' => Enum, 'p' => Pseudo, 'r' => Range, 'm' => Multirange" }
# typcategory is an arbitrary classification of data types that is used by the parser to determine which implicit casts should be “preferred”. See Table 51.65.
pg_type.typcategory = 'skip'
# Character that separates two values of this type when parsing array input. Note that the delimiter is associated with the array element data type, not the array data type.
pg_type.typdelim = { ty="i8" }
# typalign is the alignment required when storing a value of this type. It applies to storage on disk as well as most representations of the value inside PostgreSQL. When multiple values are stored consecutively, such as in the representation of a complete row on disk, padding is inserted before a datum of this type so that it begins on the specified boundary. The alignment reference is the beginning of the first datum in the sequence. Possible values are: c = char alignment, i.e., no alignment needed. s = short alignment (2 bytes on most machines). i = int alignment (4 bytes on most machines). d = double alignment (8 bytes on many machines, but by no means all).
pg_type.typalign = { ty="PgTypeTypalign", exp="PgTypeTypalign::pg_from_char(pg_type.typalign)", pgEnum="'c' => Char, 's' => Short, 'i' => Int, 'd' => Double" }
# typstorage tells for varlena types (those with typlen = -1) if the type is prepared for toasting and what the default strategy for attributes of this type should be. Possible values are: p (plain): Values must always be stored plain (non-varlena types always use this value). e (external): Values can be stored in a secondary “TOAST” relation (if relation has one, see pg_class.reltoastrelid). m (main): Values can be compressed and stored inline. x (extended): Values can be compressed and/or moved to a secondary relation. x is the usual choice for toast-able types. Note that m values can also be moved out to secondary storage, but only as a last resort (e and x values are moved first).
pg_type.typstorage = { ty="PgTypeTypstorage", exp="PgTypeTypstorage::pg_from_char(pg_type.typstorage)", pgEnum="'p' => Plain, 'e' => External, 'm' => Main, 'x' => Extended" }

pg_user_mapping = 'todo'
