
[pg_aggregate.columns.aggfnoid]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "pg_proc OID of the aggregate function"
sel = "aggfnoid::regproc::text as aggfnoid"
ty = "Qual"
exp = "Qual::parse(pg_aggregate.aggfnoid)"

[pg_aggregate.columns.aggkind]
typ = "char"
ref = ""
desc = "Aggregate kind: n for “normal” aggregates, o for “ordered-set” aggregates, or h for “hypothetical-set” aggregates"
ty = "PgAggregateAggkind"
exp = "PgAggregateAggkind::pg_from_char(pg_aggregate.aggkind)"
pgEnum = "'n' => Normal, 'o' => OrderedSet, 'h' => HypotheticalSet"

[pg_aggregate.columns.aggnumdirectargs]
typ = "int2"
ref = ""
desc = "Number of direct (non-aggregated) arguments of an ordered-set or hypothetical-set aggregate, counting a variadic array as one argument. If equal to pronargs, the aggregate must be variadic and the variadic array describes the aggregated arguments as well as the final direct arguments. Always zero for normal aggregates."
ty = "u16"
exp = "pg_aggregate.aggnumdirectargs.unsigned_abs()"

[pg_aggregate.columns.aggtransfn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Transition function"
sel = "aggtransfn::regproc::text as aggtransfn"
ty = "Qual"
exp = "Qual::parse(pg_aggregate.aggtransfn)"

[pg_aggregate.columns.aggfinalfn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Final function (zero if none)"
sel = "case when aggfinalfn = 0 then null else aggfinalfn::regproc::text end as aggfinalfn"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggfinalfn)"

[pg_aggregate.columns.aggcombinefn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Combine function (zero if none)"
sel = "case when aggcombinefn = 0 then null else aggcombinefn::regproc::text end as aggcombinefn"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggcombinefn)"

[pg_aggregate.columns.aggserialfn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Serialization function (zero if none)"
sel = "case when aggserialfn = 0 then null else aggserialfn::regproc::text end as aggserialfn"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggserialfn)"

[pg_aggregate.columns.aggdeserialfn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Deserialization function (zero if none)"
sel = "case when aggdeserialfn = 0 then null else aggdeserialfn::regproc::text end as aggdeserialfn"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggdeserialfn)"

[pg_aggregate.columns.aggmtransfn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Forward transition function for moving-aggregate mode (zero if none)"
sel = "case when aggmtransfn = 0 then null else aggmtransfn::regproc::text end as aggmtransfn"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggmtransfn)"

[pg_aggregate.columns.aggminvtransfn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Inverse transition function for moving-aggregate mode (zero if none)"
sel = "case when aggminvtransfn = 0 then null else aggminvtransfn::regproc::text end as aggminvtransfn"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggminvtransfn)"

[pg_aggregate.columns.aggmfinalfn]
typ = "regproc"
ref = "(references pg_proc.oid)"
desc = "Final function for moving-aggregate mode (zero if none)"
sel = "case when aggmfinalfn = 0 then null else aggmfinalfn::regproc::text end as aggmfinalfn"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggmfinalfn)"

[pg_aggregate.columns.aggfinalextra]
typ = "bool"
ref = ""
desc = "True to pass extra dummy arguments to aggfinalfn"
ty = "bool"

[pg_aggregate.columns.aggmfinalextra]
typ = "bool"
ref = ""
desc = "True to pass extra dummy arguments to aggmfinalfn"
ty = "bool"

[pg_aggregate.columns.aggfinalmodify]
typ = "char"
ref = ""
desc = "Whether aggfinalfn modifies the transition state value: r if it is read-only, s if the aggtransfn cannot be applied after the aggfinalfn, or w if it writes on the value"
ty = "PgAggregateAggfinalmodify"
exp = "PgAggregateAggfinalmodify::pg_from_char(pg_aggregate.aggfinalmodify)"
pgEnum = "'r' => ReadOnly, 's' => CannotApply, 'w' => Writes"

[pg_aggregate.columns.aggmfinalmodify]
typ = "char"
ref = ""
desc = "Like aggfinalmodify, but for the aggmfinalfn"
ty = "PgAggregateAggmfinalmodify"
exp = "PgAggregateAggmfinalmodify::pg_from_char(pg_aggregate.aggmfinalmodify)"
pgEnum = "'r' => ReadOnly, 's' => CannotApply, 'w' => Writes"

[pg_aggregate.columns.aggsortop]
typ = "oid"
ref = "(references pg_operator.oid)"
desc = "Associated sort operator (zero if none)"
sel = "case when aggsortop = 0 then null else aggsortop::regoperator::text end as aggsortop"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggsortop)"

[pg_aggregate.columns.aggtranstype]
typ = "oid"
ref = "(references pg_type.oid)"
desc = "Data type of the aggregate function's internal transition (state) data"
sel = "aggtranstype::regtype::text as aggtranstype"
ty = "Qual"
exp = "Qual::parse(pg_aggregate.aggtranstype)"

[pg_aggregate.columns.aggtransspace]
typ = "int4"
ref = ""
desc = "Approximate average size (in bytes) of the transition state data, or zero to use a default estimate"
skip = true

[pg_aggregate.columns.aggmtranstype]
typ = "oid"
ref = "(references pg_type.oid)"
desc = "Data type of the aggregate function's internal transition (state) data for moving-aggregate mode (zero if none)"
sel = "case when aggmtranstype = 0 then null else aggmtranstype::regtype::text end as aggmtranstype"
ty = "Option<Qual>"
exp = "Qual::maybe_parse(pg_aggregate.aggmtranstype)"

[pg_aggregate.columns.aggmtransspace]
typ = "int4"
ref = ""
desc = "Approximate average size (in bytes) of the transition state data for moving-aggregate mode, or zero to use a default estimate"
skip = true

[pg_aggregate.columns.agginitval]
typ = "text"
ref = ""
desc = "The initial value of the transition state. This is a text field containing the initial value in its external string representation. If this field is null, the transition state value starts out null."
ty = "Option<Str>"
exp = "pg_aggregate.agginitval.map(Into::into)"

[pg_aggregate.columns.aggminitval]
typ = "text"
ref = ""
desc = "The initial value of the transition state for moving-aggregate mode. This is a text field containing the initial value in its external string representation. If this field is null, the transition state value starts out null."
ty = "Option<Str>"
exp = "pg_aggregate.aggminitval.map(Into::into)"

[pg_database]
hashCol = "datname"

[pg_database.columns.oid]
typ = "oid"
ref = ""
desc = "Row identifier"
skip = true

[pg_database.columns.datname]
typ = "name"
ref = ""
desc = "Database name"
sel = "datname::text as datname"
ty = "Str"
exp = "pg_database.datname.into()"
filters = ["datname = current_database()"]

[pg_database.columns.datdba]
typ = "oid"
ref = "(references pg_authid.oid)"
desc = "Owner of the database, usually the user who created it"
sel = "pg_get_userbyid(datdba)::text as datdba"
ty = "Str"
exp = "pg_database.datdba.into()"

[pg_database.columns.encoding]
typ = "int4"
ref = ""
desc = "Character encoding for this database (pg_encoding_to_char() can translate this number to the encoding name)"
sel = "pg_encoding_to_char(encoding)::text as encoding"
ty = "Str"
exp = "pg_database.encoding.into()"

[pg_database.columns.datlocprovider]
typ = "char"
ref = ""
desc = "Locale provider for this database: b = builtin, c = libc, i = icu"
ty = "PgDatabaseDatlocprovider"
exp = "PgDatabaseDatlocprovider::pg_from_char(pg_database.datlocprovider)"
pgEnum = "'b' => Builtin, 'c' => Libc, 'i' => Icu"

[pg_database.columns.datistemplate]
typ = "bool"
ref = ""
desc = "If true, then this database can be cloned by any user with CREATEDB privileges; if false, then only superusers or the owner of the database can clone it."
ty = "bool"

[pg_database.columns.datallowconn]
typ = "bool"
ref = ""
desc = "If false then no one can connect to this database. This is used to protect the template0 database from being altered."
ty = "bool"

[pg_database.columns.dathasloginevt]
typ = "bool"
ref = ""
desc = "Indicates that there are login event triggers defined for this database. This flag is used to avoid extra lookups on the pg_event_trigger table during each backend startup. This flag is used internally by PostgreSQL and should not be manually altered or read for monitoring purposes."
skip = true

[pg_database.columns.datconnlimit]
typ = "int4"
ref = ""
desc = "Sets maximum number of concurrent connections that can be made to this database. -1 means no limit, -2 indicates the database is invalid."
sel = "case when datconnlimit < 0 then null else datconnlimit end as datconnlimit"
ty = "Option<u32>"
exp = "pg_database.datconnlimit.map(i32::unsigned_abs)"

[pg_database.columns.datfrozenxid]
typ = "xid"
ref = ""
desc = "All transaction IDs before this one have been replaced with a permanent (“frozen”) transaction ID in this database. This is used to track whether the database needs to be vacuumed in order to prevent transaction ID wraparound or to allow pg_xact to be shrunk. It is the minimum of the per-table pg_class.relfrozenxid values."
skip = true

[pg_database.columns.datminmxid]
typ = "xid"
ref = ""
desc = "All multixact IDs before this one have been replaced with a transaction ID in this database. This is used to track whether the database needs to be vacuumed in order to prevent multixact ID wraparound or to allow pg_multixact to be shrunk. It is the minimum of the per-table pg_class.relminmxid values."
skip = true

[pg_database.columns.dattablespace]
typ = "oid"
ref = "(references pg_tablespace.oid)"
desc = "The default tablespace for the database. Within this database, all tables for which pg_class.reltablespace is zero will be stored in this tablespace; in particular, all the non-shared system catalogs will be there."
skip = true

[pg_database.columns.datcollate]
typ = "text"
ref = ""
desc = "LC_COLLATE for this database"
ty = "Option<Str>"
exp = "pg_database.datcollate.map(Into::into)"

[pg_database.columns.datctype]
typ = "text"
ref = ""
desc = "LC_CTYPE for this database"
ty = "Option<Str>"
exp = "pg_database.datctype.map(Into::into)"

[pg_database.columns.datlocale]
typ = "text"
ref = ""
desc = "Collation provider locale name for this database. If the provider is libc, datlocale is NULL; datcollate and datctype are used instead."
ty = "Option<Str>"
exp = "pg_database.datlocale.map(Into::into)"

[pg_database.columns.daticurules]
typ = "text"
ref = ""
desc = "ICU collation rules for this database"
ty = "Option<Str>"
exp = "pg_database.daticurules.map(Into::into)"

[pg_database.columns.datcollversion]
typ = "text"
ref = ""
desc = "Provider-specific version of the collation. This is recorded when the database is created and then checked when it is used, to detect changes in the collation definition that could lead to data corruption."
ty = "Option<Str>"
exp = "pg_database.datcollversion.map(Into::into)"

[pg_database.columns.datacl]
typ = "aclitem[]"
ref = ""
desc = "Access privileges; see Section 5.8 for details"
sel = "datacl::text[] as datacl"
ty = "Option<Vec<aclitem::DbAclItem>>"
exp = "pg_database.datacl.map(|datacl| datacl.map(|acl| aclitem(acl, &DbGrantParser)).collect())"
