# cargo make --no-workspace mytask

[config]
default_to_workspace = false
# for tasks you *want* to run individually in members:
# workspace = true

[tasks.release]
dependencies = [
	"gen_pg_info_decisions",
	"gen_pg_info",
	"reflect_gen_queries",
	"check",
	"test",
	"do_version",
	"do_publish",
]

[tasks.do_version]
install_crate = "cargo-workspaces"
install_crate_args = ["--version", "^0.4"]
script = "cargo workspaces version --message 'v%v' --exact --no-git-push"

[tasks.do_publish]
install_crate = "cargo-workspaces"
install_crate_args = ["--version", "^0.4"]
script = "cargo workspaces publish --publish-as-is"

[tasks.check]
script = "cargo check"

[tasks.test]
script = "cargo test"


[tasks.reflect_gen_queries]
install_crate = "clorinde"
install_crate_args = ["--version", "^1.3"]
script = '''
clorinde schema ./reflect/reflect_fns.sql \
	--config ./reflect/clorinde.toml \
	--podman true \
	--container-image docker.io/library/postgres:17 \
	--queries-path ./reflect/queries \
	--destination ./reflect/queries_crate \
	--container-wait 500
'''
condition = { files_modified = { input = ["./reflect/queries/**/*", "./reflect/clorinde.toml"], output = ["./reflect/queries_crate/**/*"] } }


[tasks.reflect_dev_test]
script = "cargo test -p postgres-static-analyzer-reflect -- --nocapture"
dependencies = ["reflect_gen_queries"]


[tasks.extract_pg_info]
script = "deno run --allow-net=www.postgresql.org --allow-write --allow-read extract_pg_info.ts"
condition = { files_modified = { input = ["extract_pg_info.ts"], output = ["./extract_pg_info.local.json"] } }
# extracts the info itself, making minimal decisions

[tasks.gen_pg_info_decisions]
script = "deno run --allow-write --allow-read gen_pg_info_decisions.ts"
dependencies = ["extract_pg_info"]
# generates the decisions, using all the heuristics and overrides

[tasks.gen_pg_info]
script = "deno run --allow-write --allow-read gen_pg_info.ts"
# processes decisions into code, making minimal decisions


[tasks.full_reflect_test]
dependencies = [
	"gen_pg_info_decisions",
	"gen_pg_info",
	"reflect_dev_test",
]

[tasks.insta_review]
install_crate = "cargo-insta"
install_crate_args = ["--version", "^1.46"]
script = "cargo insta review"
