# cargo make --no-workspace mytask

[config]
default_to_workspace = false
# for tasks you *want* to run individually in members:
# workspace = true

[tasks.dev_test]
command = "cargo"
args = ["test", "--", "--nocapture"]
dependencies = ["gen_reflect"]


[tasks.test_temp_container_utils]
command = "cargo"
args = ["test", "-p", "temp_container_utils"]

[tasks.gen_reflect]
command = "clorinde"
install_crate = "clorinde"
install_crate_args = ["--version", "^1.3"]
args = [
	"schema", "empty.sql",
	"--podman", "true",
	"--container-image", "docker.io/library/postgres:17",
	"--queries-path", "reflect_queries",
	"--destination", "reflect_crate",
	"--container-wait", "500",
]
condition = { files_modified = { input = ["./reflect_queries/**/*", "./clorinde.toml"], output = ["./reflect_crate/**/*"] } }


[tasks.extract_pg_info]
command = "deno"
args = ["run", "--allow-net=www.postgresql.org", "--allow-write", "--allow-read", "extract_pg_info.ts"]
condition = { files_modified = { input = ["extract_pg_info.ts"], output = ["./extract_pg_info.local.json"] } }
# extracts the info itself, making minimal decisions

[tasks.gen_pg_info_decisions]
dependencies = ["extract_pg_info"]
command = "deno"
args = ["run", "--allow-write", "--allow-read", "gen_pg_info_decisions.ts"]
# generates the decisions, using all the heuristics and overrides

[tasks.gen_pg_info]
command = "deno"
args = ["run", "--allow-write", "--allow-read", "gen_pg_info.ts"]
# processes decisions into code, making minimal decisions


[tasks.full_test]
dependencies = [
	"gen_pg_info_decisions",
	"gen_pg_info",
	"dev_test",
]

[tasks.insta_review]
command = "cargo"
install_crate = "cargo-insta"
install_crate_args = ["--version", "^1.46"]
args = ["insta", "review"]
