use-workspace-deps = "./Cargo.toml"

[manifest.package]
name = "queries_crate"
version = "1.0.0"
description = "Reflection queries for postgres-static-analyzer."
license = "MIT"
edition = "2024"

[manifest.dependencies]
# serde = { version = "1.0", features = ["derive"] }
